apiVersion : apps/v1
kind: Deployment
metadata:
  name: "sbecoolapi-deployment"
  namespace: sbecoolapi
spec:
  replicas: 1
  selector:
    matchLabels:
      app: "sbecoolapi"
  template:
    metadata:
      labels:
        app: "sbecoolapi"
    spec:
      containers:
        - name: "sbecoolapi"
          image: "acrssbe140922.azurecr.io/sbecoolapi:1.0.0"
          ports:
          - containerPort: 3000
