apiVersion: v1
kind: Service
metadata:
    name: "sbecoolapi-service"
    namespace: sbecoolapi
    labels:
        app: "sbecoolapi"
spec:
    type: LoadBalancer
    ports:
    - port: 80
      targetPort: 3000
      protocol: TCP
      name: http
    selector:
        app: "sbecoolapi"
